aws.region=eu-west-2
aws.s3.bucket=vehicle-compliance-bucket
aws.sns.topicArn=arn:aws:sns:eu-west-2:121736505725:vehicle-compliance-topic
aws.sqs.queueUrl=https://sqs.eu-west-2.amazonaws.com/121736505725/vehicle-compliance-queue